[package]
name = "gtk-simple-todo-eight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adw = { version = "0.6.0", package = "libadwaita", features = ["v1_5"] }
gtk = { version = "0.8.2", package = "gtk4", features = ["v4_12"] }
serde = { version = "1.0.201", features = ["derive"] }
serde_json = "1.0.117"

[build-dependencies]
glib-build-tools = "0.19.0"